version: "3.4"

services:
  server:
    container_name: blog-caddy
    image: caddy
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.blog.rule: Host(`blog.localhost`)

  backend:
    container_name: blog-php
    build:
      context: .
      dockerfile: system/backend/Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini

  database:
    container_name: blog-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: blog
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

networks:
  default:
    external:
      name: proxy