version: "3.3"

services:
  server:
    container_name: blog-caddy
    image: caddy
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.blog.rule: Host(`blog.anagraph.org`)
      traefik.http.routers.blog.entrypoints: web
    networks:
      - proxy
      - blog

  backend:
    container_name: blog-php
    build:
      context: .
      dockerfile: system/backend/Dockerfile
    volumes:
      - .:/app
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini
    networks:
      - blog

  database:
    container_name: blog-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: p5blog
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

networks:
  proxy:
    external:
      name: proxy
  blog:
